-- DF Elements shop: database setup, part 2 of 3 (starting catalogue)
-- Prices are SAMPLE prices. Update them in the admin once your price list is ready.

insert into public.themes (name, subtitle, description, sort_order) values
  ('Plaas Humor', 'Afrikaans humour', 'Cheeky donkeys and Karoo sayings that make everyone smile.', 1),
  ('Karoo Hart', 'Karoo and Fraserburg', 'Sheep, windmills and a love letter to the platteland.', 2),
  ('Wild & Wonderful', 'Birds and wildlife', 'Watercolour owls and rainbow hummingbirds.', 3),
  ('Pet Portraits', 'Dogs and pets', 'Sunlit spaniel portraits, and your own pet made to order.', 4),
  ('Big Five', 'African wildlife', 'Lion, leopard, elephant, buffalo and rhino in rich gold and sepia.', 5),
  ('Petrolhead', 'Cars and bikes', 'For the ones who were born to ride.', 6),
  ('Golf', 'On the fairway', 'Tee time designs for the golfer in the family.', 7),
  ('Fishing', 'Gone fishing', 'Because the best days are spent fishing.', 8);

insert into public.products (sku, name, variant, type, theme_id, short_description, care, material, size, price, special_price, special_ends, wholesale_price, stock, is_new, is_custom, needs_review, image_url, sort_order) values
  ('CST001', 'Daai Glimlag Is Verniet', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), '"Daai glimlag is verniet, die houding kos ekstra." A grinning donkey for the coffee table.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 14, false, false, false, '/products/c_d00.webp', 1),
  ('CST002', 'Ek Bly Cool', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), 'A donkey in rainbow sunglasses who stays cool no matter what.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, 55, '2026-10-31 23:59:59+02', 39, 9, false, false, false, '/products/c_d01.webp', 2),
  ('CST003', 'Toe Raak Ek Moeg', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), '"Ek het gedink... toe raak ek moeg." For the professional napper in your life.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_d02.webp', 3),
  ('CST004', 'Geen Tyd Vir Negatiwiteit', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), '"Ek het nie tyd vir negatiwiteit nie. Waarskuwing: ek praat enige tyd!"', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 4, false, false, false, '/products/c_d10.webp', 4),
  ('CST005', 'Just Be Lekker', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), 'A close up donkey with one simple rule: just be lekker.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_d11.webp', 5),
  ('CST006', 'Fraserburg Jou Lekker Ding', '', 'coaster', (select id from public.themes where name = 'Karoo Hart'), 'A cheeky tongue out donkey with a shout out to Fraserburg.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_d12.webp', 6),
  ('CST007', 'Plaashek Oop', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), '"Leef asof jy die plaashek oop gelos het!" A donkey peeking over the farm gate.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_d20.webp', 7),
  ('CST008', 'Hemel Op Aarde', '', 'coaster', (select id from public.themes where name = 'Karoo Hart'), '"Lewe asof dit Hemel op aarde is." A happy sheep beside the windmill.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_d21.webp', 8),
  ('CST009', 'Trots Afrikaans', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), 'A proud donkey portrait with the words Trots Afrikaans.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_d22.webp', 9),
  ('CST010', 'My Hart Se Plek', '', 'coaster', (select id from public.themes where name = 'Karoo Hart'), '"My hart se plek, Fraserburg." Sheep, windmill and a big red heart.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 5, true, false, false, '/products/c_d30.webp', 10),
  ('CST011', 'Ek''s Nie Hardkoppig Nie', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), '"Ek''s nie hardkoppig nie... jy''s net verkeerd." A donkey in glasses who knows best.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, 55, '2026-10-31 23:59:59+02', 39, 10, false, false, false, '/products/c_d31.webp', 11),
  ('CST012', 'Blomme Donkie', '', 'coaster', (select id from public.themes where name = 'Plaas Humor'), 'A folk art donkey framed in leaves and bright orange flowers.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_d32.webp', 12),
  ('CST013', 'Watercolour Owl', 'Perched', 'coaster', (select id from public.themes where name = 'Wild & Wonderful'), 'A bright eyed owl in splashes of pink, gold and blue.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_o00.webp', 13),
  ('CST014', 'Watercolour Owl', 'Jewel', 'coaster', (select id from public.themes where name = 'Wild & Wonderful'), 'A bright eyed owl in splashes of pink, gold and blue.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_o01.webp', 14),
  ('CST015', 'Watercolour Owl', 'Blush', 'coaster', (select id from public.themes where name = 'Wild & Wonderful'), 'A bright eyed owl in splashes of pink, gold and blue.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_o02.webp', 15),
  ('CST016', 'Watercolour Owl', 'Sky', 'coaster', (select id from public.themes where name = 'Wild & Wonderful'), 'A bright eyed owl in splashes of pink, gold and blue.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_o10.webp', 16),
  ('CST017', 'Cavalier in the Sun', '', 'coaster', (select id from public.themes where name = 'Pet Portraits'), 'A King Charles spaniel standing tall in the afternoon light.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_o11.webp', 17),
  ('CST018', 'Daisy Field Spaniel', '', 'coaster', (select id from public.themes where name = 'Pet Portraits'), 'A happy spaniel sitting in a meadow of daisies.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_o20.webp', 18),
  ('CST019', 'Sunlit Spaniel', '', 'coaster', (select id from public.themes where name = 'Pet Portraits'), 'A smiling spaniel among the wildflowers, sun behind.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, false, false, false, '/products/c_o21.webp', 19),
  ('CST020', 'Spaniel at Play', '', 'coaster', (select id from public.themes where name = 'Pet Portraits'), 'A spaniel mid bounce with two red balls.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 3, false, false, false, '/products/c_o22.webp', 20),
  ('CST021', 'Rainbow Hummingbird', 'Splash', 'coaster', (select id from public.themes where name = 'Wild & Wonderful'), 'A hummingbird in flight trailing rainbow paint on charcoal.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_o12.webp', 21),
  ('CST022', 'Rainbow Hummingbird', 'Hover', 'coaster', (select id from public.themes where name = 'Wild & Wonderful'), 'A hummingbird in flight trailing rainbow paint on charcoal.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_o30.webp', 22),
  ('CST023', 'Rainbow Hummingbird', 'Flame', 'coaster', (select id from public.themes where name = 'Wild & Wonderful'), 'A hummingbird in flight trailing rainbow paint on charcoal.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_o31.webp', 23),
  ('CST024', 'Rainbow Hummingbird', 'Glide', 'coaster', (select id from public.themes where name = 'Wild & Wonderful'), 'A hummingbird in flight trailing rainbow paint on charcoal.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_o32.webp', 24),
  ('CST025', 'Your Pet on a Coaster', '', 'coaster', (select id from public.themes where name = 'Pet Portraits'), 'Send us a photo of your dog, cat or horse and we design and print a one of a kind coaster.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 85, null, null, null, 99, false, true, false, '/products/c_o11.webp', 25),
  ('STD026', 'Just a Boy Who Loves Cars', '', 'stand', (select id from public.themes where name = 'Petrolhead'), 'Bold blue lettering and a paint splash sports car. A perfect gift for the car mad kid.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, null, null, 87, 10, false, false, false, '/products/s_boy.webp', 26),
  ('STD027', 'Born to Ride', '', 'stand', (select id from public.themes where name = 'Petrolhead'), 'A flaming skull rider with wings of fire on a dark background.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, null, null, 87, 6, false, false, false, '/products/s_born.webp', 27),
  ('STD028', 'Born to Ride', 'Smoke', 'stand', (select id from public.themes where name = 'Petrolhead'), 'A cruiser bike rising out of silver smoke.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, null, null, 87, 10, false, false, false, '/products/s_smoke.webp', 28),
  ('STD029', 'Unmatched', '', 'stand', (select id from public.themes where name = 'Petrolhead'), 'A sports car exploding into neon paint. Unmatched.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, 125, '2026-10-31 23:59:59+02', 87, 10, false, false, false, '/products/s_unmatched.webp', 29),
  ('STD030', 'Fairway Memories', '', 'stand', (select id from public.themes where name = 'Golf'), 'A sweeping green fairway with a golfer mid swing.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, null, null, 87, 10, false, false, true, '/products/s_golf1.webp', 30),
  ('STD031', 'Eat Sleep Golf Repeat', '', 'stand', (select id from public.themes where name = 'Golf'), 'Eat. Sleep. Golf. Repeat. With a ball on the tee on the base.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, null, null, 87, 10, false, false, false, '/products/s_golf2.webp', 31),
  ('STD032', 'Tee Off', '', 'stand', (select id from public.themes where name = 'Golf'), 'Putter, ball and bright red tee on a sunny green.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, null, null, 87, 2, false, false, true, '/products/s_golf3.webp', 32),
  ('STD033', 'Best Days Are Spent Fishing', '', 'stand', (select id from public.themes where name = 'Fishing'), 'A leaping fish badge over a soft pattern of fish.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, null, null, 87, 10, false, false, false, '/products/s_fish1.webp', 33),
  ('STD034', 'Gone Fishing', '', 'stand', (select id from public.themes where name = 'Fishing'), 'Handwritten Gone Fishing with a hook and line, on a fish print background.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 145, null, null, 87, 10, false, false, false, '/products/s_fish2.webp', 34),
  ('STD035', 'Your Photo Phone Stand', '', 'stand', (select id from public.themes where name = 'Pet Portraits'), 'Your pet, family or favourite place printed on a phone stand, with a name or message if you like.', 'Slot the front panel into the base and stand your phone in the ledge. Wipe clean with a damp cloth.', 'MDF, two pieces, UV printed front and base.', '', 175, null, null, null, 99, false, true, false, '/products/s_born.webp', 35),
  ('CST036', 'The Big Five', 'Five Lives', 'coaster', (select id from public.themes where name = 'Big Five'), '"Five lives. One wild Africa." Lion, leopard, elephant, buffalo and rhino side by side in gold.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_b1.webp', 36),
  ('CST037', 'The Big Five', 'Sepia', 'coaster', (select id from public.themes where name = 'Big Five'), '"Wild. Beautiful. Irreplaceable." The Big Five in a warm sepia watercolour with script lettering.', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_b2.webp', 37),
  ('CST038', 'The Big Five', 'Five Legends', 'coaster', (select id from public.themes where name = 'Big Five'), '"Five legends of Africa. Each unique. Each vital. All worth protecting."', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_b3.webp', 38),
  ('CST039', 'Power & Patience', '', 'coaster', (select id from public.themes where name = 'Big Five'), 'A Cape buffalo in gold and black. "Stand firm. Stay calm. Keep going."', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_b4.webp', 39),
  ('CST040', 'Gentle Giant', '', 'coaster', (select id from public.themes where name = 'Big Five'), 'An elephant bull walking out of the dark. "Remember. Respect. Protect."', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_b5.webp', 40),
  ('CST041', 'Silent Hunter', '', 'coaster', (select id from public.themes where name = 'Big Five'), 'A leopard in golden light. "Watch. Wait. Pounce. Survive."', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_b6.webp', 41),
  ('CST042', 'King of Africa', '', 'coaster', (select id from public.themes where name = 'Big Five'), 'A lion with a golden crown. "Lead with strength. Rule with heart."', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_b7.webp', 42),
  ('CST043', 'Ancient Survivor', '', 'coaster', (select id from public.themes where name = 'Big Five'), 'A rhino in rich sepia gold. "Overcoming against all odds."', 'Place on any flat surface. Wipe clean with a damp cloth and let it dry. Keep out of standing water and the dishwasher.', 'MDF, UV printed on the top face.', '', 65, null, null, 39, 10, true, false, false, '/products/c_b8.webp', 43);

with s as (insert into public.gift_sets (name, description, price, sort_order) values ('Big Five Set of 5', 'King of Africa, Silent Hunter, Gentle Giant, Power & Patience and Ancient Survivor in one gold gift set.', 275, 1) returning id)
insert into public.gift_set_items (gift_set_id, product_id, qty) select s.id, p.id, 1 from s, public.products p where p.sku in ('CST042', 'CST041', 'CST040', 'CST039', 'CST043');

with s as (insert into public.gift_sets (name, description, price, sort_order) values ('Plaas Humor Set of 4', 'Four of our cheekiest donkeys to keep the coffee table laughing.', 220, 2) returning id)
insert into public.gift_set_items (gift_set_id, product_id, qty) select s.id, p.id, 1 from s, public.products p where p.sku in ('CST001', 'CST002', 'CST003', 'CST005');

with s as (insert into public.gift_sets (name, description, price, sort_order) values ('Watercolour Owl Set of 4', 'All four watercolour owls in one gift ready set.', 220, 3) returning id)
insert into public.gift_set_items (gift_set_id, product_id, qty) select s.id, p.id, 1 from s, public.products p where p.sku in ('CST013', 'CST014', 'CST015', 'CST016');

with s as (insert into public.gift_sets (name, description, price, sort_order) values ('Hummingbird Set of 4', 'Four rainbow hummingbirds on charcoal.', 220, 4) returning id)
insert into public.gift_set_items (gift_set_id, product_id, qty) select s.id, p.id, 1 from s, public.products p where p.sku in ('CST021', 'CST022', 'CST023', 'CST024');

with s as (insert into public.gift_sets (name, description, price, sort_order) values ('Spaniel Set of 4', 'Four sunny spaniel portraits for the dog lover.', 220, 5) returning id)
insert into public.gift_set_items (gift_set_id, product_id, qty) select s.id, p.id, 1 from s, public.products p where p.sku in ('CST017', 'CST018', 'CST019', 'CST020');

with s as (insert into public.gift_sets (name, description, price, sort_order) values ('Karoo Hart Trio', 'Fraserburg, the happy sheep and My Hart Se Plek together.', 170, 6) returning id)
insert into public.gift_set_items (gift_set_id, product_id, qty) select s.id, p.id, 1 from s, public.products p where p.sku in ('CST006', 'CST008', 'CST010');

with s as (insert into public.gift_sets (name, description, price, sort_order) values ('Gone Fishing Pair', 'Both fishing phone stands, one for home and one for the office.', 260, 7) returning id)
insert into public.gift_set_items (gift_set_id, product_id, qty) select s.id, p.id, 1 from s, public.products p where p.sku in ('STD033', 'STD034');

insert into public.delivery_options (name, description, rate, sort_order) values
  ('Courier to your door', 'Economy, 2 to 4 working days', 99, 1),
  ('Express courier', 'Overnight to main centres', 160, 2),
  ('Collect from a PUDO locker', 'Choose a locker near you, 3 to 5 working days', 69, 3);

update public.settings set specials_end = '2026-10-31 23:59:59+02' where id = 1;
