-- DF Elements: brochure designs (one page per design, many formats)
-- Run once in the Supabase SQL Editor, after 12_faith_and_inspiration_themes.sql.

-- ============ NEW TABLES ============
create table public.formats (
  key text primary key,
  label text not null,
  group_name text not null,
  product_type text not null references public.product_types(key),
  price numeric(10,2),
  trade_price numeric(10,2),
  cost_item_id bigint references public.cost_items(id) on delete set null,
  sort_order int not null default 0,
  is_active boolean not null default true
);

create table public.designs (
  id bigint generated always as identity primary key,
  code text not null unique,
  name text not null,
  theme_id bigint references public.themes(id) on delete set null,
  language text not null default 'en' check (language in ('af','en','none')),
  wording text not null default '',
  description text not null default '',
  short_description text not null default '',
  gift_for text not null default '',
  image_url text,
  page_url text,
  is_new boolean not null default true,
  is_active boolean not null default true,
  needs_review boolean not null default true,
  review_notes text not null default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.products
  add column design_id bigint references public.designs(id) on delete cascade,
  add column format_key text references public.formats(key) on update cascade;
create index on public.products (design_id);

alter table public.formats enable row level security;
alter table public.designs enable row level security;
create policy "formats read" on public.formats for select using (true);
create policy "formats staff" on public.formats for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "designs read" on public.designs for select using (is_active or public.is_staff());
create policy "designs staff" on public.designs for all to authenticated using (public.is_staff()) with check (public.is_staff());

-- ============ NEW THEMES ============
insert into public.themes (name, subtitle, description, sort_order) select 'Coffee', 'Coffee time', 'Coffee lovers, fresh beans and koffietyd.', 30 where not exists (select 1 from public.themes where name = 'Coffee');
insert into public.themes (name, subtitle, description, sort_order) select 'Wine', 'Wine time', 'For the wine lovers and the friends you share a glass with.', 30 where not exists (select 1 from public.themes where name = 'Wine');
insert into public.themes (name, subtitle, description, sort_order) select 'School and Kids', 'Teachers and classrooms', 'Gifts for teachers, classrooms and little learners.', 30 where not exists (select 1 from public.themes where name = 'School and Kids');
insert into public.themes (name, subtitle, description, sort_order) select 'Christmas', 'Kersfees', 'Festive designs for the holidays.', 30 where not exists (select 1 from public.themes where name = 'Christmas');
insert into public.themes (name, subtitle, description, sort_order) select 'Colour Me', 'Colour it yourself', 'Black and white line art to colour in yourself.', 30 where not exists (select 1 from public.themes where name = 'Colour Me');
insert into public.themes (name, subtitle, description, sort_order) select 'Proteas', 'Our national flower', 'King proteas and pinks in every style.', 30 where not exists (select 1 from public.themes where name = 'Proteas');
insert into public.themes (name, subtitle, description, sort_order) select 'Friendship', 'Forever friends', 'For the friends who feel like family.', 30 where not exists (select 1 from public.themes where name = 'Friendship');
insert into public.themes (name, subtitle, description, sort_order) select 'Flowers and Botanicals', 'Blooms and greenery', 'Vintage blooms, succulents and roses.', 30 where not exists (select 1 from public.themes where name = 'Flowers and Botanicals');

-- ============ COSTING CARDS FOR SMALL ITEMS (estimates, check in Costing) ============
insert into public.cost_items (name, width_mm, height_mm, notes, sort_order)
select v.n, v.w, v.h, 'Estimated size, please check', v.s from (values
  ('Key ring', 50, 40, 20), ('Button 30 mm', 30, 30, 21), ('Ruler 30 cm', 320, 40, 22), ('Ruler 15 cm', 170, 40, 23)
) as v(n, w, h, s) where not exists (select 1 from public.cost_items c where c.name = v.n);

-- ============ FORMATS ============
insert into public.formats (key, label, group_name, product_type, price, trade_price, cost_item_id, sort_order) values
  ('a3', 'A3 board', 'Boards', 'board', 56, 36, (select id from public.cost_items where name = 'A3 board' limit 1), 1),
  ('a4', 'A4 board', 'Boards', 'board', 38, 21.5, (select id from public.cost_items where name = 'A4 board' limit 1), 2),
  ('sq300', '300 x 300 board', 'Boards', 'board', 50, 29, (select id from public.cost_items where name = 'Board 300 x 300' limit 1), 3),
  ('rnd300', '300 x 300 round board', 'Boards', 'board', 50, 29, (select id from public.cost_items where name = 'Board 300 x 300' limit 1), 4),
  ('cst_sq', 'Coaster square', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 10),
  ('cst_rnd', 'Coaster round', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 11),
  ('cst_hex', 'Coaster hexagon', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 12),
  ('cst_cup', 'Coaster cup', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 13),
  ('cst_teacup', 'Coaster teacup', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 14),
  ('cst_teapot', 'Coaster teapot', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 15),
  ('cst_sugar', 'Coaster sugar pot', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 16),
  ('cst_scallop', 'Coaster scallops', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 17),
  ('cst_leaf', 'Coaster leaf', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 18),
  ('cst_grapes', 'Coaster grapes', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 19),
  ('cst_heart', 'Coaster heart', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 20),
  ('cst_other', 'Coaster special shape', 'Coasters', 'coaster', 12, 7, (select id from public.cost_items where name = 'Coaster' limit 1), 21),
  ('kr1', 'Keyring 1', 'Keyrings and buttons', 'gifts', 15, 8.5, (select id from public.cost_items where name = 'Key ring' limit 1), 30),
  ('kr2', 'Keyring 2', 'Keyrings and buttons', 'gifts', 15, 8.5, (select id from public.cost_items where name = 'Key ring' limit 1), 31),
  ('kr3', 'Keyring 3', 'Keyrings and buttons', 'gifts', 15, 8.5, (select id from public.cost_items where name = 'Key ring' limit 1), 32),
  ('btn1', 'Button 1 (pack of 6)', 'Keyrings and buttons', 'gifts', 10, 4, (select id from public.cost_items where name = 'Button 30 mm' limit 1), 33),
  ('btn2', 'Button 2 (pack of 6)', 'Keyrings and buttons', 'gifts', 10, 4, (select id from public.cost_items where name = 'Button 30 mm' limit 1), 34),
  ('btn3', 'Button 3 (pack of 6)', 'Keyrings and buttons', 'gifts', 10, 4, (select id from public.cost_items where name = 'Button 30 mm' limit 1), 35),
  ('door', 'Door hanger', 'Other', 'gifts', 25, 14.5, (select id from public.cost_items where name = 'Door hanger' limit 1), 40),
  ('stand', 'Phone stand', 'Other', 'stand', 25, 14.5, (select id from public.cost_items where name = 'Phone stand' limit 1), 41),
  ('ruler30', 'Ruler 30 cm', 'Other', 'gifts', 18, 11, (select id from public.cost_items where name = 'Ruler 30 cm' limit 1), 42),
  ('ruler15', 'Ruler 15 cm', 'Other', 'gifts', 18, 11, (select id from public.cost_items where name = 'Ruler 15 cm' limit 1), 43);

-- ============ DESIGNS ============
insert into public.designs (code, name, theme_id, language, wording, description, short_description, gift_for, image_url, page_url, review_notes, sort_order) values
  ('BLOMME INSP_001', 'Doen Meer Van Dit Wat Jou Gelukkig Maak', (select id from public.themes where name = 'Inspiration'), 'af', 'Doen meer van dit wat jou gelukkig maak', '"Doen meer van dit wat jou gelukkig maak" staan sag teen ''n warm oranje sonsondergang, met ''n boom waarvan die blare skoenlappers is. ''n Rustige herinnering vir enigiemand wat ''n bietjie vreugde in die dag nodig het. Beskikbaar op borde, onderleggers, sleutelringe, knopies en meer.', 'Sonsondergang en skoenlappers met ''n blymoedige herinnering', '''n goeie vriendin, jou ma, iemand wat ''n nuwe begin maak', '/designs/blomme_insp_001/a3.webp', '/designs/pages/b01-1.webp', 'Cellphone stand upright and base detected as one box (4). Hexagon coaster and keyrings 1 and 3 show only the tree, no wording.', 1),
  ('BLOMME INSP_002', 'Koester Jou Hartsmense, Die Lewe Is Kort', (select id from public.themes where name = 'Inspiration'), 'af', 'Koester jou hartsmense die lewe is kort', 'Helder geverfde blomme in blougroen, goudgeel, magenta en pers, met hier en daar ''n kolibrie, omraam die woorde "Koester jou hartsmense, die lewe is kort". Dit is ''n liefdevolle geskenk vir die mense wat die naaste aan jou hart lê. Kry dit op borde, onderleggers, sleutelringe, liniale en meer.', 'Kleurvolle blomme met ''n boodskap vir jou hartsmense', 'jou beste vriendin, familie, iemand wat jy mis', '/designs/blomme_insp_002/a3.webp', '/designs/pages/b01-2.webp', 'Floral collection where almost every item uses a different flower painting: A3 has a yellow and purple flower on teal, A4 a white daisy with an orange text panel, the square 300 board is a white peony with no words, the round 300 board a yellow flower with pink mandala lines, the stand shows hummingbirds. Kept as one design because all share the theme and no sensible split exists; owner may want to check. Label reads COASTER SCOLOPS (should be SCALLOPS). Ruler label is just RULER; scale runs to 30 cm. Stand upright and base are one box (4). No 300 X 300 BOARD wording on the square board.', 2),
  ('BLOMME INSP_003', 'Saai Die Goeie En Die Mooi Sal Daaruit Groei', (select id from public.themes where name = 'Inspiration'), 'af', 'Saai die goeie en die mooi sal daaruit groei', 'Sonnige geel sonneblomme teen ''n ryk bruin houtpatroon dra die boodskap "Saai die goeie en die mooi sal daaruit groei". Dit pas pragtig in ''n plaaskombuis of enige huis met ''n warm hart. Beskikbaar op borde, onderleggers, sleutelringe, knopies, deurhangers en meer.', 'Sonneblomme op hout met ''n boodskap oor goedheid', 'tuiniers, ''n nuwe huis, onderwysers, jou ouma', '/designs/blomme_insp_003/a3.webp', '/designs/pages/b01-3.webp', 'Round 300 board, hexagon and cup coasters, door hanger, stand and keyrings show sunflowers only without wording. Stand upright and base are one box (4).', 3),
  ('BLOMME INSP_004', 'Tussen Die Onkruid Is Daar Steeds Die Mooiste Blomme', (select id from public.themes where name = 'Inspiration'), 'af', 'Tussen die onkruid is daar steeds die mooiste blomme', '''n Vrolike dogtertjie in ''n geel rokkie en rooi stewels spring deur geel lelies, met die woorde "Tussen die onkruid is daar steeds die mooiste blomme". Dit herinner ons dat daar altyd iets moois te vind is, selfs op moeilike dae. Kry dit op borde, onderleggers, sleutelringe en meer.', 'Speelse ontwerp wat die mooi in elke dag raaksien', 'iemand wat swaar kry, ''n dogterkamer, ''n goeie vriendin', '/designs/blomme_insp_004/a3.webp', '/designs/pages/b01-4.webp', 'Page is missing almost all format labels (no A3/A4/300 board, coaster, door hanger, cellphone stand or button labels; the ORDER CODE caption is also missing). Keyring labels overlap each other and appear in a different font. Formats assigned by shape and position: please check. Features a photo of a real child, so confirm image rights. Stand upright and base are one box (4).', 4),
  ('BLOMME INSP_006', 'Tuis By Die Huis', (select id from public.themes where name = 'Inspiration'), 'af', 'Tuis by die huis', 'Sagte waterverfprente van families in groen weivelde vol pienk blomme, onder ''n blou lug, met die woorde "Tuis by die huis" in sterk rooi letters. Dit is ''n warm welkom vir enige voordeur of gesinskamer. Beskikbaar op borde, onderleggers, sleutelringe, deurhangers en meer.', 'Waterverf gesinstonele vir ''n huis vol liefde', '''n nuwe huis, jong gesinne, jou ouers', '/designs/blomme_insp_006/a3.webp', '/designs/pages/b01-5.webp', 'Each item shows a different watercolour family scene (parents lifting a child, couple holding hands, cycling family) with the same wording; kept as one design. Lettering is maroon on A3/A4 but bright red on the 300 boards. Only one button (labelled BUTTON 30MM). Code jumps from INSP_004 to INSP_006; check whether INSP_005 exists. Stand upright and base are one box (4).', 5),
  ('BLOMME INSP_014', 'Omring Jou Met Mense Wat Jou Laat Blom', (select id from public.themes where name = 'Inspiration'), 'af', 'Omring jou met mense wat jou laat blom', 'Geel rose en oranje tulpe met herfsblare raam ''n blou denimagtergrond, met die goue woorde "Omring jou met mense wat jou laat blom". ''n Mooi manier om dankie te sê vir die vriende wat jou lewe ryker maak. Kry dit op borde, onderleggers, sleutelringe, knopies en meer.', 'Rose, tulpe en denim vir die mense wat jou laat blom', 'vriendinne, kollegas, ''n mentor, jou suster', '/designs/blomme_insp_014/a3.webp', '/designs/pages/b01-6.webp', 'Code jumps from INSP_006 to INSP_014 between consecutive pages; check for missing designs 007 to 013. Hexagon coaster and keyring 1 have flowers only, no wording. Keyring 3 label sits under box 11 and keyring 2 under box 12. Stand upright and base are one box (4).', 6),
  ('COFFEE ENG_006', 'Coffee Time', (select id from public.themes where name = 'Coffee'), 'en', 'Coffee time', 'A cosy chalkboard design that simply says "Coffee time", with white sketched coffee pots, cups and leaves around rich brown beans and a real espresso cup. Perfect for the kitchen, a home office or your favourite coffee corner. Choose it on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Chalkboard coffee art for your favourite cuppa corner', 'coffee lovers, a new kitchen, colleagues, morning people', '/designs/coffee_eng_006/a3.webp', '/designs/pages/b02-1.webp', 'Secondary words on the art: espresso, Fresh Beans. Hexagon coaster shows only Fresh Beans; round coaster is a photo of an espresso cup on a saucer; cup coaster shows espresso and beans. Keyrings 2 and 3 are mug shaped. Stand upright and base are one box (4).', 7),
  ('COLOUR_ME_001', 'Colour Me Flowers and Butterflies', (select id from public.themes where name = 'Colour Me'), 'none', '', 'Black and white line drawings of flowers, leaves and butterflies, ready for you to colour in yourself. A calm, creative project for a quiet afternoon, and lovely for crafty kids and grown ups alike. Printed to order on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Flowers and butterflies, ready for you to colour in', 'crafty kids, creative friends, a rainy day, art lovers', '/designs/colour_me_001/a3.webp', '/designs/pages/b02-2.webp', 'Colouring in range, no wording. A3 and A4 are an all over flower pattern; square 300 board has a framed butterfly centre, round 300 board a butterfly and dragonfly ring. Round coaster and keyring 3 show a mandala with pink cut lines. Keyring 1 is flower shaped, keyring 2 butterfly shaped. Code uses underscores in place of a space (COLOUR_ME_001), unlike other codes. Stand upright and base are one box (4).', 8),
  ('COLOUR_ME_002', 'Don''t Worry About Tomorrow', (select id from public.themes where name = 'Faith and Blessings'), 'en', 'Has anyone by fussing in front of the mirror ever gotten taller by so much as an inch? All this time and money wasted on fashion, do you think it makes that much difference? Instead of looking at the fashions, walk out into the fields and look at the wildflowers. They never primp or shop, but have you ever seen color and design quite like it? The ten best-dressed men and women in the country look shabby alongside them. Matthew 6:27-29 MSG', 'Sketched wildflower bouquets meet royal blue watercolour, rustic wood and blush pink satin around the words of Matthew 6:27 to 29 (MSG): "walk out into the fields and look at the wildflowers." A gentle reminder not to worry about tomorrow. Comes on boards, coasters, keyrings, rulers and more.', 'Wildflowers and Matthew 6 for a heart that worries less', 'friends of faith, worriers, Bible study groups, a new home', '/designs/colour_me_002/a3.webp', '/designs/pages/b02-3.webp', 'Detector found no code but the page shows ORDER CODE COLOUR_ME_002. Mixed page kept as one design because backgrounds and texts are scattered across items with no clean grouping: A3 is blue with the English Matthew 6:27-29 MSG text; square 300 board (wood), keyring 1, door hanger (purple galaxy) and ruler say Don''t worry about tomorrow, Matthew 6:34; round 300 board (pink) and cup coaster (blue) carry the same passage in Afrikaans (Wie tog onder julle kan ... Matthew 6:28); A4 is a pink framed bouquet with no words. Owner may prefer to split into English and Afrikaans products. Afrikaans reference is printed Mattheus 6:28 (modern spelling Matteus; passage is really 6:27 to 29). Label reads COASTER SCOLOPS (should be SCALLOPS). Keyring 2 is a blue blob shape with no clear artwork; check it. Stand upright and base are one box (4).', 9),
  ('KERSFEES_001', 'Geseënde Kersfees', (select id from public.themes where name = 'Christmas'), 'af', 'Geseënde Kersfees', 'Grillige getekende Kersfeeskarakters soos sneeumanne, ''n beertjie en hasie, Kersvader, kabouters en rendiere op agtergronde van sagte blou en bruinpapier, met die groet "Geseënde Kersfees". Dit bring feestelike vreugde na enige huis in Desember. Beskikbaar op borde, onderleggers, sleutelringe, liniale en meer.', 'Speelse Kersfeeskarakters met ''n geseënde groet', 'onderwysers, kinders, bure, Kersboomgeskenkies', '/designs/kersfees_001/a3.webp', '/designs/pages/b02-4.webp', 'Christmas collection: almost every format uses a different illustration (A3 three snowmen ''Geseënde Kersfees'', 300 board bear and bunny ''Geseënde Kersfees'', round board Santa ''Ho Ho Ho'', A4 Santa, tree and snowman without words, gnome coasters, reindeer, girl keyring). Kept as one design because the extra artworks cannot be grouped into sensible sets; owner may want to sell boards as separate designs. Door hanger reads ''moenie my pla nie ek wag vir Kersvader!''. Button 3 is heart shaped (gingerbread heart). Coaster cup label is split over two lines (COASTER / CUP).', 10),
  ('KOFFIE AFR_003', 'Dis Altyd Koffietyd', (select id from public.themes where name = 'Coffee'), 'af', 'Dis altyd koffietyd', 'Koffiebone, gemaalde koffie en kaneelstokkies op ''n donker leiklipagtergrond, met die woorde "Dis altyd koffietyd" in wit skrif. Perfek vir die kombuis, die kantoor of enigiemand wat nie sonder ''n koppie kan begin nie. Kry dit op borde, onderleggers, sleutelringe, knopies en meer.', 'Vir die koffieliefhebber wat weet dis altyd koffietyd', 'koffieliefhebbers, kollegas, ''n nuwe kombuis', '/designs/koffie_afr_003/a3.webp', '/designs/pages/b02-5.webp', 'Artwork prints ''dis altyd Koffie tyd'' (lower case ''dis'', ''Koffie tyd'' as two words); correct Afrikaans is ''Dis altyd koffietyd''. Hexagon coaster, keyring 1 and keyring 3 show coffee beans only (no words); coaster round shows coffee photo without words. Button 3 is a wider (heart/oval) shape.', 11),
  ('FLOWER INSP_101', 'Begin Each Day With A Grateful Heart', (select id from public.themes where name = 'Inspiration'), 'en', 'Begin each day with a grateful heart', 'White daisies and fresh green leaves frame the words "Begin each day with a grateful heart" on a deep navy background. A quiet, uplifting piece for a bedside table, kitchen or office desk. Available on boards, coasters, keyrings, buttons, rulers and door hangers.', 'White daisies and a gentle reminder to start the day grateful', 'friends, teachers, a new home, Mother''s Day', '/designs/flower_insp_101/a3.webp', '/designs/pages/b03-1.webp', 'Page has no labels and an empty order code box (font problem); formats identified by position and shape against b03-2. Page shows four different quotes in one daisy on navy series, split into four designs; wordless daisy items (door hanger, plain keyring, buttons, ruler) placed here. Square coaster reads ''Follow your dreams'' (different quote, same series). Coaster in the cup position is a round daisy mandala, not a cup shape, so listed as cst_other. A3 lettering is laid out as ''Begin EACH WITH DAY (A) grateful HEART''; check reading order.', 12),
  ('FLOWER INSP_101B', 'Be The Reason Someone Smiles Today', (select id from public.themes where name = 'Inspiration'), 'en', 'Be the reason someone smiles today', 'A cascade of white daisies tumbles beside cream and sage lettering that says "Be the reason someone smiles today." Simple, kind and cheerful, it suits anyone who brightens a room just by walking in. Choose it as a square board, a keyring or a phone stand.', 'Daisies and a kind nudge to make someone smile', 'kind hearted friends, nurses, teachers, colleagues', '/designs/flower_insp_101b/sq300.webp', '/designs/pages/b03-1.webp', '300 x 300 board, cellphone stand and keyring 1 carry this quote. No code printed.', 13),
  ('FLOWER INSP_101C', 'Love Laughter And Happily Ever After', (select id from public.themes where name = 'Inspiration'), 'en', 'Love, laughter and happily ever after', 'Gold and green script reads "Love, laughter and happily ever after" inside a wreath of white daisies on navy, shaped like a little speech bubble. A sweet keepsake for newlyweds, anniversaries or a romantic bedroom. Available as a round board and as round coasters.', 'A daisy wreath for love, laughter and happily ever after', 'newlyweds, anniversaries, engagements, a bridal shower', '/designs/flower_insp_101c/rnd300.webp', '/designs/pages/b03-1.webp', 'Board in the 300 x 300 round position is a speech bubble shape (round with a pointed corner), not a plain circle; the coaster in the round coaster position has the same bubble shape with an empty daisy wreath. Check format keys. No code printed.', 14),
  ('FLOWER INSP_101D', 'Best Things In Life Are Free', (select id from public.themes where name = 'Inspiration'), 'en', 'Best things in life are free', 'A heart shaped navy design with a wreath of white daisies around lime yellow lettering that reminds us the "Best things in life are free." Warm, simple and full of feeling, it is a lovely way to say thank you. Comes as a board, heart coasters and keyrings.', 'A daisy heart reminding us the best things are free', 'best friends, Valentine''s Day, grandparents, a thank you', '/designs/flower_insp_101d/a4.webp', '/designs/pages/b03-1.webp', 'A4 board is heart shaped; heart coaster (in hexagon position) and heart keyring show an empty daisy heart wreath. No code printed.', 15),
  ('FLOWER INSP_002', 'Surround Yourself With People Who Allow You To Blossom', (select id from public.themes where name = 'Inspiration'), 'en', 'Surround yourself with people who allow you to blossom', 'White lilies and soft pink roses rest on vintage script paper beside elegant calligraphy: "Surround yourself with people who allow you to blossom." A graceful piece for a dear friend or a feminine living space. Choose from boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Lilies, roses and a reminder to keep your people close', 'close friends, sisters, mentors, Mother''s Day', '/designs/flower_insp_002/a3.webp', '/designs/pages/b03-2.webp', 'Hexagon coaster, keyring 1 and keyring 3 show flowers only (no words). Cellphone stand label cut off at page edge.', 16),
  ('FLOWER INSP_003', 'Every Single Moment Matters', (select id from public.themes where name = 'Inspiration'), 'en', 'Every single moment matters', 'Autumn maple leaves in red, orange, yellow and green drift across a cream watercolour wash, with bold brush lettering saying "Every single moment matters." Warm and grounding, it suits a reading nook or study. Available on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Autumn leaves and a reminder that every moment counts', 'retirees, graduates, a new chapter, friends', '/designs/flower_insp_003/a3.webp', '/designs/pages/b03-3.webp', 'Button 1 is labelled ''BUTTON 30MM'' instead of ''BUTTON 1''. Hexagon coaster, cup coaster and keyring 3 show leaves only (no words).', 17),
  ('FLOWER INSP_102', 'Every Love Story Is Beautiful But Ours Is My Favourite', (select id from public.themes where name = 'Inspiration'), 'en', 'Every love story is beautiful but ours is my favourite', 'Pastel wildflowers and little hearts float on a soft pink watercolour background around vintage type: "Every love story is beautiful but ours is my favourite." A tender gift for your partner on an anniversary or Valentine''s Day. Comes on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Pastel flowers for the love story that is your favourite', 'your partner, anniversaries, Valentine''s Day, newlyweds', '/designs/flower_insp_102/a3.webp', '/designs/pages/b03-4.webp', 'No format labels except buttons and empty order code box (font problem); formats identified by position against b03-2. Only two keyrings: a heart keyring (box 10, spanning the keyring 1 and 2 positions) and a rounded rectangle keyring (box 11); assigned kr1 and kr2, owner should confirm keyring numbers. Square coaster shows flowers only (no words). Button 3 is heart shaped.', 18),
  ('FLOWER INSP_008', 'Tropical Parrot with Hibiscus', (select id from public.themes where name = 'Flowers and Botanicals'), 'none', '', 'A bright orange and yellow parrot perches among pink hibiscus, bird of paradise and palm leaves on bold geometric diamonds of red, lime and turquoise. Pure holiday energy for a patio, beach house or any room that needs a splash of colour. Available on boards, coasters, keyrings, buttons and more.', 'A tropical parrot bursting with holiday colour', 'bird lovers, a beach house, patio entertainers, colourful souls', '/designs/flower_insp_008/a3.webp', '/designs/pages/b03-5.webp', 'No words on the design. Round board and several small items use a tropical leaf wreath or plain diamond pattern without the parrot. Third board label reads ''300 X 300'' (round board label split over lines).', 19),
  ('FLOWER INSP_103', 'You Will Never Have This Day Again So Make It Count', (select id from public.themes where name = 'Inspiration'), 'en', 'You will never have this day again so make it count', 'Pink, blue and orange paisley swirls bloom across whitewashed wood planks, with bold lettering declaring "You will never have this day again so make it count." Bright and motivating, it suits a home office, gym corner or teen''s room. Choose from boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Colourful paisley and a push to make today count', 'graduates, go getters, teens, colleagues', '/designs/flower_insp_103/a3.webp', '/designs/pages/b03-6.webp', 'Labels missing except buttons and empty order code box (font problem); formats identified by position against b03-2. Door hanger, hexagon and square coasters, keyrings 1 and 3 show paisley on wood without words. Button 3 is heart shaped.', 20),
  ('FLOWER INSP_011', 'Begin Each Day With A Grateful Heart', (select id from public.themes where name = 'Inspiration'), 'en', 'Begin each day with a grateful heart', 'Red and pink tulips, orange blooms and berries frame dark lettering on a rustic wood panel: "Begin each day with a grateful heart." A warm farmhouse style piece for the kitchen or breakfast nook. Available on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Rustic tulips and a grateful start to every day', 'a new home, mothers, grandmothers, farmhouse kitchens', '/designs/flower_insp_011/a3.webp', '/designs/pages/b03-7.webp', 'A3 board is a shaped cut out (wood panel with tulip bouquets either side); round board is a half wood circle with tulips spilling out. Hexagon coaster and cellphone stand read ''Made with Love'' (different quote, same series). Lettering laid out as ''Begin EACH WITH DAY A grateful HEART''. Label ''CELLPHONE STAND'' sits above the stand next to the keyrings; door hanger label overlaps the stand.', 21),
  ('FLOWER INSP_011B', 'There Are So Many Beautiful Reasons To Be Happy', (select id from public.themes where name = 'Inspiration'), 'en', 'There are so many beautiful reasons to be happy', 'Red tulips and ripe strawberries tumble down beside the words "There are so many beautiful reasons to be happy" on rustic wood. Fresh, cheerful and a little country, it brightens any kitchen. Choose it as a square board, square coasters or a keyring.', 'Tulips, strawberries and plenty of reasons to be happy', 'a new home, friends, kitchen lovers, a cheer up gift', '/designs/flower_insp_011b/sq300.webp', '/designs/pages/b03-7.webp', '300 x 300 board, square coaster and keyring 3 use this different quote and black background; split from the main design on the same page (code FLOWER INSP_011).', 22),
  ('MAP_001', 'Animal World Map', (select id from public.themes where name = 'School and Kids'), 'none', '', 'A bright turquoise world map where every continent is full of cartoon animals, from penguins to whales and other sea creatures. Fun and educational, it is perfect for a playroom, classroom or little explorer''s bedroom. Available on boards, keyrings and rulers.', 'A colourful animal world map for little explorers', 'kids, teachers, classrooms, young travellers', '/designs/map_001/a3.webp', '/designs/pages/b04-1.webp', 'A4 is a different but related picture (cartoon lion, zebra, penguin and friends standing on a globe). Keyrings (penguin, monkey, owl) and both rulers (row of cartoon animals) grouped here by theme. Page mixes three artworks, split into three designs.', 23),
  ('MAP_001B', 'Small Acts Change the World', (select id from public.themes where name = 'School and Kids'), 'en', 'Small acts change the world', 'Cream lettering over a dark world map on blue grey wood says "Small acts change the world," partnered with colourful painted globe coasters. A thoughtful message for a classroom, an office or anyone who quietly makes a difference. Choose it as a square board or as coasters.', 'A world map reminding us small acts matter', 'teachers, volunteers, nurses, community heroes', '/designs/map_001b/sq300.webp', '/designs/pages/b04-1.webp', 'Coasters show watercolour/3D globes rather than the board art; coaster cup has different wording ''Ready for new adventures'' on dark wood. Grouped here by world/globe theme, owner may prefer separate listings.', 24),
  ('MAP_001C', 'Give Africa Some Colour', (select id from public.themes where name = 'School and Kids'), 'en', 'Give Africa some colour', 'An outline map of Africa waits to be coloured in, surrounded by sketched giraffe, elephant, parrot, xerus and other animals on a sky blue circle. "Give Africa some colour" makes a fun, proudly local activity for kids. Available as a round board, door hanger and phone stand.', 'Colour in Africa and its animals yourself', 'kids, teachers, crafty families, proudly South African friends', '/designs/map_001c/rnd300.webp', '/designs/pages/b04-1.webp', 'Colour in board with animal labels (Grey Parrot, Xerus, Chevrotain, Elephant, Elephant Shrew, Giraffe, Indri, Jacana). Door hanger (cartoon giraffe on wood) and cellphone stand (African woman in colourful headwrap dancing, on wood) grouped here by African theme; check.', 25),
  ('MOOI AFR_006', 'Elke Pot Het ''n Deksel', (select id from public.themes where name = 'Inspiration'), 'af', 'Elke pot het ''n deksel, elke foto het ''n raam, elke sprokie het een of ander tyd regtig bestaan', 'Wit madeliefies, pienk gerberas, geel freesias en ''n silwer teepot omring ''n houtfotoraam teen ''n diep donkerblou agtergrond. Die woorde "Elke pot het ''n deksel, elke foto het ''n raam" herinner ons dat sprokies soms regtig bestaan. Beskikbaar op borde, onderleggers, sleutelringe en meer.', 'Blomme, ''n teepot en ''n boodskap oor ware liefde', '''n bruid, ''n verloofde paar, jou ma, ''n romantikus', '/designs/mooi_afr_006/a3.webp', '/designs/pages/b04-2.webp', 'Order code was not picked up by the detector; read from page as MOOI AFR_006. Round coaster is labelled only ''COASTER ROUND'' in image but detected as ''COASTER''.', 26),
  ('MOOI AFR_004', 'Jy Sal Nooit Weer Hierdie Dag Hê Nie', (select id from public.themes where name = 'Inspiration'), 'af', 'Jy sal nooit weer hierdie dag hê nie, so maak die beste van dit', 'Pastelblou en pienk ruitpatroon met monstera en palmblare in waterverf, in groen, mosterdgeel en pruimkleur dra die boodskap "Jy sal nooit weer hierdie dag hê nie, so maak die beste van dit". ''n Opgewekte aansporing vir elke oggend. Kry dit op borde, onderleggers, sleutelringe, knopies en meer.', 'Tropiese blare met ''n aansporing om vandag te geniet', '''n gegradueerde, ''n goeie vriendin, ''n nuwe werk', '/designs/mooi_afr_004/a3.webp', '/designs/pages/b04-3.webp', 'Artwork prints ''HE'' without the circumflex (should be ''hê''). A4 board is a plain plum monstera leaf shape with no wording. Detector read the code as ''AF R_004''; page shows MOOI AFR_004.', 27),
  ('MOOI AFR_001', 'Blom Soos Kosmos', (select id from public.themes where name = 'Inspiration'), 'af', 'Blom soos kosmos, want ''n glimlag, vriendelikheid, omgee en liefde kos mos niks', 'Sagte pienk kosmosblomme, perkamentpapier en ''n pienk kolletjieslint omring die woorde "Blom soos kosmos, want ''n glimlag, vriendelikheid, omgee en liefde kos mos niks". ''n Nostalgiese ontwerp met ''n speelse woordspeling wat elke Afrikaanse hart sal laat glimlag. Beskikbaar op borde, onderleggers, sleutelringe en meer.', 'Kosmosblomme en ''n oulike woordspeling oor omgee', 'jou ouma, ''n vriendin, onderwysers, ''n dankiegeskenk', '/designs/mooi_afr_001/a3.webp', '/designs/pages/b04-4.webp', 'Round coaster labelled ''COASTER ROUND'' (detector read only ''COASTER''). Hexagon coaster shows only background and ribbon, no wording. Detector read code as ''MOO AFR_001''.', 28),
  ('PRET ENG_001', 'Let''s Go for a Ride', (select id from public.themes where name = 'Petrolhead'), 'en', 'Let''s go for a ride', 'Vintage classic cars in yellow, burgundy, cream and red cruise through a sepia sketched street, with bold script inviting "Let''s go for a ride." Made for petrolheads, garage walls and anyone who loves an old school road trip. Comes on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Classic cars and a nostalgic invitation to hit the road', 'petrolheads, dads, car club members, a garage or man cave', '/designs/pret_eng_001/a3.webp', '/designs/pages/b05-1.webp', 'Each board shows a different vintage car with the same wording. Order code not picked up by detector; read from page as PRET ENG_001. Door hanger has no car or wording, only the sketched street background.', 29),
  ('PRET ENG_002', 'Live Love Laugh', (select id from public.themes where name = 'Inspiration'), 'en', 'Live every moment, love beyond words, laugh every day', 'Large white lettering on aged golden parchment reads "Live every moment, love beyond words, laugh every day," surrounded by watercolour tulips, daffodils, lavender and wildflowers. A warm, timeless message for a living room or entrance hall. Available on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Watercolour flowers around the classic live, love, laugh', 'a new home, mothers, friends, housewarmings', '/designs/pret_eng_002/a3.webp', '/designs/pages/b05-2.webp', 'Artwork spells ''everyday'' as one word; should be ''every day''. Round board shows only ''Live Love Laugh''. Hexagon coaster shows a butterfly on a daisy, no wording.', 30),
  ('PRET ENG_003', 'Ask Me About My Cat', (select id from public.themes where name = 'Pet Portraits'), 'en', 'Ask me about my cat', 'A whimsical girl with her bicycle and flower basket is joined by orange tabby kittens on a mint green grid with a pink scalloped border. "Ask me about my cat" is made for proud cat parents everywhere. Choose from a board, coasters, keyrings, buttons, rulers, a door hanger and a phone stand.', 'For proud cat parents who love to talk about their cat', 'cat lovers, girls, cat sitters, vets', '/designs/pret_eng_003/a3.webp', '/designs/pages/b05-3.webp', 'Page mixes several whimsical girl artworks; split into four designs. Cellphone stand (''99% cute 1% cheeky'' girl with cats), door hanger (''Girls only'' girl), ruler and buttons (green doodle flowers, alarm clock) grouped here by green style. Keyring 1 (''Small acts change the world'', orange) and coaster cup (''You make me happy'', turquoise) don''t match any board; grouped here, owner to check.', 31),
  ('PRET ENG_003B', 'Life Is a Beautiful Ride', (select id from public.themes where name = 'Inspiration'), 'en', 'Life is a beautiful ride', 'A red haired girl zips along on a pink scooter with her tabby kittens and little hearts, under the words "Life is a beautiful ride." Playful and sweet, it is lovely for a girl''s bedroom or a cat loving friend. Available as a square board.', 'A scooter, kittens and a beautiful ride through life', 'girls, cat lovers, a bedroom, birthdays', '/designs/pret_eng_003b/sq300.webp', '/designs/pages/b05-3.webp', 'Only the 300 board shows this artwork.', 32),
  ('PRET ENG_003C', 'Birthday Girl with Cake and Puppy', (select id from public.themes where name = 'Inspiration'), 'none', '', 'A curly haired girl hugs her puppy beside a birthday cake and bunting, set in a mint green circle with pink scallops. Cheerful and full of party spirit, it makes a sweet birthday keepsake or bedroom decoration. Comes as a round board and as round and square coasters.', 'A birthday girl, her puppy and a cake to celebrate', 'birthday girls, dog lovers, daughters, party favours', '/designs/pret_eng_003c/rnd300.webp', '/designs/pages/b05-3.webp', 'Square coaster shows a different girl with a ''Happy Birthday'' cake; grouped here by birthday theme.', 33),
  ('PRET ENG_003D', 'You Can Do Anything You Want', (select id from public.themes where name = 'Inspiration'), 'en', 'You can do anything you want', 'Ornate white script on soft mauve says "You can do anything you want," framed by a border of yellow, white and blue daisies. An encouraging piece for a young dreamer, a student or anyone starting something new. Available as a board and a keyring.', 'Daisies and a confident reminder you can do anything', 'daughters, students, graduates, a new job', '/designs/pret_eng_003d/a4.webp', '/designs/pages/b05-3.webp', 'Keyring 2 (daisy bouquet) grouped here by flower style.', 34),
  ('PRET ENG_004', 'Life Is a Beautiful Journey', (select id from public.themes where name = 'Inspiration'), 'en', 'Life is a beautiful journey', 'Old maps, a compass, pocket watch, telescope and wooden plane gather around a parchment scroll and white orchids, reading "Life is a beautiful journey." Made for travellers, adventurers and anyone starting a new chapter. Comes on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Vintage maps and compass for life''s beautiful journey', 'travellers, retirees, graduates, a farewell gift', '/designs/pret_eng_004/a3.webp', '/designs/pages/b05-4.webp', 'Round coaster shows only a brass compass. Several labels were only partly detected but all are printed on the page.', 35),
  ('PRET ENG_005', 'A Friend Overlooks Your Broken Fence', (select id from public.themes where name = 'Friendship'), 'en', 'A friend is one who overlooks your broken fence and admires the flowers in your garden', 'Two little friends lean on a wooden fence in a watercolour autumn scene of mountains, trees and sunflowers, beside the words "A friend is one who overlooks your broken fence and admires the flowers in your garden." A heartfelt thank you to a true friend. Available as a board, button, keyring, door hanger and phone stand.', 'A gentle watercolour tribute to friends who see the good', 'best friends, neighbours, a thank you, old friends', '/designs/pret_eng_005/a3.webp', '/designs/pages/b05-5.webp', 'Friendship themed page with four different board artworks; split into four designs. Door hanger and keyring 2 (''True friends only'', two kids walking) grouped here by matching art style. Cellphone stand and button 1 show watercolour wood/tree with pink blossom; grouped here, check. Coaster label ''SCOLOPS'' is misspelt (should be SCALLOP).', 36),
  ('PRET ENG_005B', 'A Friend Understands Your Past', (select id from public.themes where name = 'Friendship'), 'en', 'A friend is someone who understands your past, believes in your future, and accepts you just the way you are', 'Two women sit together beneath an arch of soft watercolour wildflowers and leaves, with the words "A friend is someone who understands your past, believes in your future, and accepts you just the way you are." A tender gift for a lifelong friend. Available as a square board and scalloped coasters.', 'Watercolour wildflowers for a friend who truly gets you', 'best friends, sisters, lifelong friends, a birthday', '/designs/pret_eng_005b/sq300.webp', '/designs/pages/b05-5.webp', 'Scallop coaster shows a watercolour rainbow with ''Try to be a rainbow in someone''s cloud''; grouped here by watercolour style.', 37),
  ('PRET ENG_005C', 'Forever Friends', (select id from public.themes where name = 'Friendship'), 'en', 'Forever friends', 'Two little girls sit side by side in a meadow of daisies, with pink stripes and yellow tulip wreath accents and the words "Forever friends." Sweet and nostalgic, it suits best friends of any age. Choose from a round board, coasters, keyrings, buttons and a ruler.', 'Two little girls in the daisies, friends forever', 'best friends, school friends, sisters, birthdays', '/designs/pret_eng_005c/rnd300.webp', '/designs/pages/b05-5.webp', 'Round coaster, keyring 3, ruler (''I get by with a little help from my friends'', The Beatles) and buttons share the pink stripe and tulip style. Teacup coaster (two girls from behind), square coaster and keyring 1 (''Laughter is my best friend'', two laughing girls) grouped here; owner may want these separate.', 38),
  ('PRET ENG_005D', 'A Sweet Friendship Refreshes the Soul', (select id from public.themes where name = 'Friendship'), 'en', 'A sweet friendship refreshes the soul. Proverbs 27:9', 'A row of children with their arms around each other stands under a purple jacaranda style tree, with Proverbs 27:9: "A sweet friendship refreshes the soul." A gentle, faith filled reminder of good friends. Available as an A4 board.', 'Children under a jacaranda and a verse about friendship', 'friends of faith, Sunday school teachers, school friends', '/designs/pret_eng_005d/a4.webp', '/designs/pages/b05-5.webp', 'Only the A4 board shows this artwork.', 39),
  ('PRET ENG_006', 'Be the Best Version of Yourself', (select id from public.themes where name = 'Inspiration'), 'en', 'Be the best version of yourself', 'Pale green succulents and eucalyptus rest on grey marble with fine gold geometric lines, beside dark green script: "Be the best version of yourself." Calm, modern and quietly motivating, it suits a home office or dressing table. Choose from boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Modern marble and succulents for your best self', 'colleagues, graduates, fitness friends, a new office', '/designs/pret_eng_006/a3.webp', '/designs/pages/b05-6.webp', 'Cellphone stand upright and base detected as one box (4).', 40),
  ('PROTEA_001', 'White King Protea on Wood', (select id from public.themes where name = 'Proteas'), 'none', '', 'A creamy white king protea with deep green leaves stands out against warm brown and orange wooden planks. Proudly South African and naturally elegant, it suits a farmhouse kitchen, lodge or holiday home. Available on boards, coasters, keyrings, buttons, rulers, door hangers and phone stands.', 'A white king protea on warm rustic wood', 'proudly South African friends, guesthouses, a new home, visitors from abroad', '/designs/protea_001/a3.webp', '/designs/pages/b06-1.webp', 'A4 board and square coaster use a different crop showing protea buds at the sides rather than one central flower; 300 board shows a cluster of three proteas. Cellphone stand detected as one box (4).', 41),
  ('PROTEA_002', 'Lag, Bid, Gee', (select id from public.themes where name = 'Proteas'), 'af', 'Lag dit maak jou gelukkiger. Bid dit maak jou sterker. Gee dit maak jou ryker.', 'Pienk en rooi koningsproteas met saliegroen blare teen ''n witgewaste baksteenmuur, met die woorde "Lag dit maak jou gelukkiger. Bid dit maak jou sterker. Gee dit maak jou ryker." Plaaslik, trots en vol hoop. Kry dit op borde, onderleggers, sleutelringe, liniale en meer.', 'Koningsproteas met ''n boodskap oor lag, bid en gee', 'gelowige vriende, jou ma, ''n nuwe huis, gaste uit die buiteland', '/designs/protea_002/a3.webp', '/designs/pages/b06-2.webp', 'Only the A3 board carries the wording; all other items show the protea art without text. Two items labelled 300 X 300 BOARD: box 1 is square, box 0 is a scalloped protea bouquet shape (no round board on this page). A4 board has a stone texture background instead of brick. Coaster 8 is labelled just COASTER (bouquet cutout shape). Cellphone stand detected as one box (4).', 42),
  ('PROTEA_003', 'Painted King Protea', (select id from public.themes where name = 'Proteas'), 'none', '', 'An expressive king protea in blush pink, peach and orange with a cream centre, painted in loose oil strokes on soft teal and grey. Artistic and proudly South African, it brings real warmth to a living room or studio. Comes on boards, coasters, keyrings, buttons, rulers, door hangers and phone stands.', 'An expressive oil painted king protea in soft blush tones', 'art lovers, visitors from abroad, a new home, mothers', '/designs/protea_003/a3.webp', '/designs/pages/b06-3.webp', 'Each format uses a different protea painting in the same painterly style (300 board is deeper crimson, A4 is muted olive and beige, round coaster has a mandala border). Cellphone stand detected as one box (4).', 43),
  ('PROTEA_004', 'Blush Protea Blossoms', (select id from public.themes where name = 'Proteas'), 'none', '', 'Coral pink and peach proteas mingle with cherry blossoms, white berries and green sprigs on a blush linen texture. Soft, pretty and gently South African, it suits a bedroom, guest room or sunny kitchen. Available on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Blush proteas and cherry blossoms in soft pretty tones', 'mothers, bridesmaids, a guest room, friends overseas', '/designs/protea_004/a3.webp', '/designs/pages/b06-4.webp', 'Order code printed in lowercase as ''protea_004'' and page uses a different font from other pages. Labels overlap and run off the right edge (DOOR HANGER and CELLPHONE STAND cut off; ''COASTER Hexagon'' mixed case). Box 13 also contains the 30MM text. No ruler on this page. Cellphone stand detected as one box (4).', 44),
  ('PROTEA_007', 'Framed Proteas and Hummingbird', (select id from public.themes where name = 'Proteas'), 'none', '', 'Pink watercolour proteas and roses spill from an ornate white frame, joined by a hummingbird, feathers and red berries on a mint green wash. Romantic and full of life, it makes a lovely piece for a garden lover. Choose from boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Watercolour proteas, roses and a hummingbird on mint', 'garden lovers, bird lovers, mothers, a bridal shower', '/designs/protea_007/a3.webp', '/designs/pages/b06-5.webp', 'Code jumps from PROTEA_004 (previous page) to PROTEA_007; check whether 005 and 006 exist elsewhere. No ruler on this page. Cellphone stand detected as one box (4).', 45),
  ('PROTEA_008', 'For I Know the Plans I Have for You', (select id from public.themes where name = 'Faith and Blessings'), 'en', 'For I know the plans I have for you declares the Lord, plans for peace not evil and a hope. Jeremiah 29:11', 'Deep crimson proteas and eucalyptus frame a white diamond panel with a gold border and the words of Jeremiah 29:11: "For I know the plans I have for you declares the Lord." A hopeful blessing for a new season. Available on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Crimson proteas around the promise of Jeremiah 29:11', 'friends of faith, graduates, a new chapter, confirmations', '/designs/protea_008/a3.webp', '/designs/pages/b06-6.webp', 'Round coaster, keyring 2 and keyring 3 show only the proteas without the verse. Only one button (BUTTON 30MM). No ruler. Cellphone stand detected as one box (4).', 46),
  ('PROTEA_009', 'Proteas and Roses on Periwinkle', (select id from public.themes where name = 'Proteas'), 'none', '', 'Watercolour pink proteas, crimson roses and sage leaves frame a dreamy periwinkle and sky blue wash. Soft and romantic with a local touch, it suits a bedroom, bathroom or entrance hall. Available on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Proteas and roses on a dreamy periwinkle wash', 'mothers, grandmothers, a new home, friends overseas', '/designs/protea_009/a3.webp', '/designs/pages/b06-7.webp', 'Round board and square coaster use a wreath arrangement of the same flowers. No ruler. Cellphone stand detected as one box (4).', 47),
  ('PROTEA_010', 'God Se Plan Vir Jou Lewe', (select id from public.themes where name = 'Faith and Blessings'), 'af', 'God se plan vir jou lewe, is altyd GROTER en MOOIER as wat jy kan DINK of DROOM!', '''n Ry helder pienk en rooi koningsproteas onder sierlike pienk krulle, met die woorde "God se plan vir jou lewe is altyd GROTER en MOOIER as wat jy kan DINK of DROOM!" ''n Bemoedigende geloofsboodskap vir iemand wat op ''n nuwe pad is. Beskikbaar op borde, onderleggers, sleutelringe en meer.', 'Proteas en ''n bemoedigende boodskap oor God se plan', '''n gegradueerde, iemand met ''n nuwe begin, gelowige vriende', '/designs/protea_010/a3.webp', '/designs/pages/b06-8.webp', 'Hexagon and square coasters, keyrings 1 and 2 show proteas without text; keyring 3 and button show only the pink swirl pattern. Round coaster has the wording set in a circle. Only one button (BUTTON 30MM). No ruler. Cellphone stand detected as one box (4).', 48),
  ('TYPO INSP_001', 'Follow Your Dreams', (select id from public.themes where name = 'Inspiration'), 'en', 'Follow your dreams', 'Bold white lettering on black says "Follow your dreams," framed by bright retro daisies, flowers and butterflies. Fun, colourful and full of encouragement, it is perfect for a teen''s room or a study desk. Choose from a board, coasters, keyrings, buttons, a ruler and a phone stand.', 'Retro daisies and butterflies urging you to follow your dreams', 'teens, students, graduates, dreamers', '/designs/typo_insp_001/a3.webp', '/designs/pages/b07-1.webp', 'Mixed quote page: boards are four different designs, split accordingly. Leftover items kept here though several carry other quotes: round coaster ''Positive Vibes Only'' (purple), cup coaster and keyring 1 ''Begin each day with a grateful heart'', cellphone stand ''Do more of what makes you happy'' with floral base. Square coaster, keyring 3, buttons and ruler show only the black floral pattern. Cellphone stand detected as one box (4).', 49),
  ('TYPO INSP_001B', 'Love, Laughter and Happily Ever After', (select id from public.themes where name = 'Inspiration'), 'en', 'Love, laughter and happily ever after', 'Pink, yellow, mint and lilac script reads "Love, laughter and happily ever after," sprinkled with little hearts and stars on black. Sweet and cheerful, it suits a girl''s bedroom or a newlywed couple. Available as a square board, a keyring and a door hanger.', 'Pastel script and hearts for a happily ever after', 'newlyweds, girls, a bridal shower, couples', '/designs/typo_insp_001b/sq300.webp', '/designs/pages/b07-1.webp', 'Keyring 2 is heart shaped with this quote.', 50),
  ('TYPO INSP_001C', 'Dream Believe Imagine Always', (select id from public.themes where name = 'Inspiration'), 'en', 'Dream, believe, imagine, always', 'A teal rocket ship blasts off among orange and pink planets and stars on a round black board, with the words "Dream, believe, imagine, always." Made for little astronauts and big imaginations, it is a fun addition to any child''s room. Available as a round board.', 'A rocket among the planets for big imaginations', 'kids, space fans, a nursery, birthdays', '/designs/typo_insp_001c/rnd300.webp', '/designs/pages/b07-1.webp', 'Only the round 300 board carries this design.', 51),
  ('TYPO INSP_001D', 'Dream Big', (select id from public.themes where name = 'Inspiration'), 'en', 'Dream big', 'Chunky doodle letters in red, yellow, pink, purple and teal shout "Dream big," surrounded by stars and swirls in a fun cut out shape. Bright and playful, it is ideal for a child''s room or a creative space. Comes as an A4 board and as coasters.', 'Colourful doodle letters telling you to dream big', 'kids, teens, students, creative souls', '/designs/typo_insp_001d/a4.webp', '/designs/pages/b07-1.webp', 'A4 board and Coaster 1 are cut to the lettering shape.', 52),
  ('VETPLANTE_004', 'Green Succulents on Linen', (select id from public.themes where name = 'Flowers and Botanicals'), 'none', '', 'Soft watercolour succulents, eucalyptus and tiny white blossoms rest on grey linen with thin gold geometric frames. Calm, fresh and modern, it suits plant lovers and minimalist spaces alike. Choose from boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Soft green succulents with a touch of gold', 'plant lovers, a new office, a new home, colleagues', '/designs/vetplante_004/a3.webp', '/designs/pages/b07-2.webp', 'No ruler on this page. Round board and round coaster have a blank white circle in the centre (possibly space for personalisation). Buttons 1 and 2 show only the grey linen texture. Cellphone stand detected as one box (4).', 53),
  ('VINFLOW_001', 'Music Is the Soundtrack of Your Life', (select id from public.themes where name = 'Inspiration'), 'en', 'Music is the soundtrack of your life. Dick Clark', 'Vintage sheet music lies on dark weathered wood beneath blue anemones, purple hellebores and greenery, with white script quoting Dick Clark: "Music is the soundtrack of your life." A beautiful piece for musicians and music lovers. Available on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Vintage sheet music and flowers for every music lover', 'musicians, music teachers, choir members, music lovers', '/designs/vinflow_001/a3.webp', '/designs/pages/b08-1.webp', 'Same artwork throughout but two quotes: A3 and cup coaster say ''Music is the soundtrack of your life'' (Dick Clark); 300 board, A4 and keyring 1 say ''Without music, life is a journey through a desert'' (Pat Conroy). Kept as one design; owner may want to list the Pat Conroy boards separately. No ruler on this page. Cellphone stand detected as one box (4).', 54),
  ('VINFLOW_002', 'Vintage Botanical Flowers', (select id from public.themes where name = 'Flowers and Botanicals'), 'none', '', 'Vintage botanical illustrations of magenta nasturtiums, a pink poppy, lilac bellflowers and pale irises sit on rich navy, teal and dark backgrounds. Elegant and timeless, it suits a study, library corner or classic living room. Available on boards, coasters, keyrings, buttons, rulers, door hangers and phone stands.', 'Vintage botanical flowers on rich, moody backgrounds', 'garden lovers, book lovers, grandmothers, a new home', '/designs/vinflow_002/a3.webp', '/designs/pages/b08-2.webp', 'Each item shows a different vintage flower illustration (nasturtium A3, poppy 300 board, bellflowers round board, iris A4 and door hanger, peony square coaster, red poppies round coaster) in a shared style, so kept as one collection design. Cellphone stand detected as one box (4).', 55),
  ('VINFLOW_003', 'Dutch Still Life Flowers', (select id from public.themes where name = 'Flowers and Botanicals'), 'none', '', 'In the style of an old master Dutch still life, tulips, roses, irises and peonies spill from a vase against a dark background with gold accents. Rich and dramatic, it brings gallery elegance to a dining room or study. Choose from boards, teapot and teacup coasters, keyrings, rulers and more.', 'Old master Dutch flowers with rich gold accents', 'art lovers, tea lovers, grandmothers, a dining room', '/designs/vinflow_003/a3.webp', '/designs/pages/b08-3.webp', 'Round board has a gold lace doily frame. Cellphone stand (4) and keyring 2 (15) show a pastel stack of floral teacups, a different artwork from the still life; check they belong here. Label ''COASTER SCOLOPS'' misspelled (should be SCALLOPS). Sugar pot label partly covered by keyring 1. Cellphone stand detected as one box (4).', 56),
  ('VINFLOW_003B', 'Life Is Full of Possibilities', (select id from public.themes where name = 'Inspiration'), 'en', 'Life is full of possibilities', 'Red roses, peonies, hydrangeas and greenery surround a gold framed white square on black, with navy script reading "Life is full of possibilities." Lush and optimistic, it is a lovely gift for someone starting a new chapter. Available as a square board.', 'Lush roses framing a hopeful message about possibilities', 'graduates, a new job, retirees, friends', '/designs/vinflow_003b/sq300.webp', '/designs/pages/b08-3.webp', 'Only the 300 board carries this design.', 57),
  ('WINE_001', 'Save Water Drink Wine', (select id from public.themes where name = 'Wine'), 'en', 'Save water, drink wine', 'Pink and burgundy watercolour splashes surround a sketched wine glass and navy script declaring "Save water, drink wine." Cheeky and fun, it belongs on the bar, braai area or kitchen wall. Comes on a board, grape coasters, keyrings, buttons, a ruler and a door hanger.', 'A cheeky wine motto for the bar or kitchen', 'wine lovers, girlfriends, hostesses, a birthday', '/designs/wine_001/a3.webp', '/designs/pages/b09-1.webp', 'Button 3 (small wine barrel) was not detected as a box, so it is missing from the items. Leftover items kept here: grapes coaster, keyrings (vine leaf, grape bunch, wine barrel) and buttons (vine leaf, pink watercolour). Ruler label reads just ''RULER'' (assumed 30 cm).', 58),
  ('WINE_001B', 'Wine Is Always a Great Idea', (select id from public.themes where name = 'Wine'), 'en', 'Wine is always a great idea', 'White lettering on plum says "Wine is always a great idea," with sketched purple grapes, green vine leaves and a wine glass. A playful nod for anyone who enjoys a good glass at the end of the day. Available as a square board and a phone stand.', 'Grapes, vines and the reminder that wine is always good', 'wine lovers, hostesses, colleagues, a birthday', '/designs/wine_001b/sq300.webp', '/designs/pages/b09-1.webp', 'Cellphone stand uses this quote over two clinking glasses on pink watercolour. Cellphone stand detected as one box (4).', 59),
  ('WINE_001C', 'Wine Tasting Is My Favourite Sport', (select id from public.themes where name = 'Wine'), 'en', 'Wine tasting is my favourite sport', 'A white wine bottle, glass and ornate grape vine wreath sit on a round plum background with the words "Wine tasting is my favourite sport." Perfect for Winelands weekenders and wine club regulars. Available as a round board and round coasters.', 'Plum and vines for those whose favourite sport is wine tasting', 'wine club members, wine lovers, hosts, a birthday', '/designs/wine_001c/rnd300.webp', '/designs/pages/b09-1.webp', 'Artwork spells ''favorite'' (US spelling); owner may want ''favourite''.', 60),
  ('WINE_001D', 'Wine Time', (select id from public.themes where name = 'Wine'), 'en', 'Wine time', 'A hand drawn red wine bottle, corks, glass and swirls sit with black lettering announcing "Wine time" on a crisp white background. Simple, fun and ready for sundowners. Choose it as an A4 board, leaf coasters or square coasters.', 'Simple sketched wine art announcing it is wine time', 'wine lovers, hosts, a housewarming, girlfriends', '/designs/wine_001d/a4.webp', '/designs/pages/b09-1.webp', 'Square coaster says ''Wine Not?'' in the same illustrated style. Leaf coaster label reads ''COASTER LEAVE'' (should be LEAF).', 61),
  ('WINE_002', 'Friendship Is the Wine of Life', (select id from public.themes where name = 'Wine'), 'en', 'Friendship is the wine of life', 'Red wine pours into a glass beside purple grapes and corks on rustic brown wooden planks, with the words "Friendship is the wine of life." A warm toast to good company, made for friends who share a bottle. Choose from a board, coasters, keyrings, buttons, a ruler, a door hanger and a phone stand.', 'Rustic wine art raising a glass to friendship', 'best friends, wine lovers, hosts, book club', '/designs/wine_002/a3.webp', '/designs/pages/b09-2.webp', 'Mixed quote page split by board. Leftover items kept here carry other wording: door hanger ''Password: wine'' swirl, cellphone stand ''Wine, juice with more life experience'', hexagon ''Let''s drink together'' (chalkboard), square and scallop coasters ''Time to wine down'', round coaster ''It''s wine o''clock somewhere'', keyring 1 ''Wine tasting is my favorite sport'' (matches WINE_001). Label ''COASTER SCOLOPS'' misspelled (should be SCALLOPS). Cellphone stand detected as one box (4).', 62),
  ('WINE_002B', 'Keep Calm and Pour On', (select id from public.themes where name = 'Wine'), 'en', 'Keep calm & pour on', 'A crystal glass of red wine, blue grapes and scattered corks sit on warm brown wood beneath white lettering that says "Keep calm & pour on." A relaxed, cheerful piece for the bar, patio or kitchen. Available as a square board.', 'Keep calm and pour on with a glass of red', 'wine lovers, hosts, dads, a braai area', '/designs/wine_002b/sq300.webp', '/designs/pages/b09-2.webp', 'Only the 300 board carries this design.', 63),
  ('WINE_002C', 'Moderation', (select id from public.themes where name = 'Wine'), 'en', 'Who is this ''Moderation'' everyone tells me to drink with?', 'A bunch of blue grapes, green vine leaves, a glass of red and corks rest on dark wooden planks with a cheeky question: "Who is this ''Moderation'' everyone tells me to drink with?" Guaranteed to make wine lovers smile. Available as a round board.', 'A cheeky question about who Moderation really is', 'wine lovers, friends with humour, hosts, a birthday', '/designs/wine_002c/rnd300.webp', '/designs/pages/b09-2.webp', 'Quote curves around the top edge; first word partly hidden at the left edge, check wording.', 64),
  ('WINE_002D', 'If One Glass of Wine Is Good for You', (select id from public.themes where name = 'Wine'), 'en', 'If one glass of wine is good for you... just imagine what a whole bottle could do!', 'Red wine bottles, glasses, grapes and corks crowd warm brown wooden planks beside dark script: "If one glass of wine is good for you... just imagine what a whole bottle could do!" A tongue in cheek gift for the wine lover with a sense of humour. Available as an A4 board.', 'One glass is good, so imagine a whole bottle', 'wine lovers, girlfriends, hosts, a birthday', '/designs/wine_002d/a4.webp', '/designs/pages/b09-2.webp', 'Only the A4 board carries this design.', 65),
  ('ROSES_001', 'When Life Throws Thorns, Look for Roses', (select id from public.themes where name = 'Inspiration'), 'en', 'When life throws thorns, look for roses', 'Red, coral and white roses with green leaves frame the words "When life throws thorns, look for roses" on white marble with a black lattice and gold frame. Elegant and encouraging, it is a lovely gift for someone going through a hard season. Choose from boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Elegant roses and encouragement for the thorny days', 'a friend in a tough season, mothers, colleagues, a get well gift', '/designs/roses_001/a3.webp', '/designs/pages/b10-1.webp', 'Box 1 contains both the round 300 board and the door hanger (detected as one box), so it is listed under rnd300 and door. Round board wording differs: ''Take time to smell the roses''.', 66),
  ('ROSES_005', 'Vintage Cream Roses on Damask', (select id from public.themes where name = 'Flowers and Botanicals'), 'none', '', 'Vintage cream and blush pink cabbage roses with soft green leaves bloom over an olive gold damask wallpaper pattern. Romantic and old world, it suits a country cottage, guest bedroom or tea corner. Available on boards, coasters, keyrings, buttons, door hangers and phone stands.', 'Vintage cabbage roses on an elegant gold damask', 'grandmothers, mothers, tea lovers, a country cottage', '/designs/roses_005/a3.webp', '/designs/pages/b10-2.webp', 'Order code printed in lowercase (''roses_005''). Labels overlap and are cut off at the page edge (DOOR HANGER, CELLPHONE STAND, 30MM); layout differs from other pages. Hexagon coaster shows only damask pattern, no roses.', 67),
  ('SCHOOL_001', 'Sometimes You Win, Sometimes You Learn', (select id from public.themes where name = 'School and Kids'), 'en', 'Sometimes you win, sometimes you learn', 'White chalk doodles of school items cover a dark chalkboard, with rainbow lettering on other pieces reading "Sometimes you win, sometimes you learn." A positive message for classrooms, students and anyone learning from setbacks. Available on boards, coasters, keyrings, rulers, door hangers and phone stands.', 'Chalkboard doodles and a growth mindset message', 'teachers, students, coaches, end of year gifts', '/designs/school_001/a3.webp', '/designs/pages/b10-3.webp', 'Chalkboard school theme with a different quote on each piece: 300 board ''Mistakes allow thinking to happen'', round board Tom Bodett school vs life quote, A4 ''Math the only subject that counts'', door hanger and cup ''Life is full of possibilities'', stand ''Dreams are not something to wait for, they are something to work for'', round coaster ''Kindness matters''. A4 board shows a ''designed by freepik'' credit that should be checked for licensing. No buttons on this page.', 68),
  ('SCHOOL_002', 'Math Teacher: Like a Normal Teacher but Way Cooler', (select id from public.themes where name = 'School and Kids'), 'en', 'Math Teacher (noun): like a normal teacher but way cooler', 'Cartoon school supply characters play along a numbered board game path on light wood, with the definition "Math Teacher (noun): like a normal teacher but way cooler." A fun thank you for the maths teacher in your life. Comes on boards, coasters, keyrings, rulers, door hangers and phone stands.', 'For the maths teacher who is way cooler', 'maths teachers, end of year gifts, tutors, Teachers'' Day', '/designs/school_002/a3.webp', '/designs/pages/b10-4.webp', 'Board game theme on wood; quotes vary per piece: ''Make your mistakes work 4 you by learning from them!'', ''Math the only subject that counts'', ''In this room we don''t do easy, we make easy happen through hard work and learning''. Small attribution under ''Make your mistakes'' quote should be checked. No buttons on this page.', 69),
  ('SCHOOL_003', 'Education Is Our Passport to the Future', (select id from public.themes where name = 'School and Kids'), 'en', 'Education is our passport to the future, for tomorrow belongs to the people who prepare for it today. Malcolm X', 'Watercolour school supplies, from a red apple and pencils to books, a backpack and a paint palette, surround Malcolm X''s words: "Education is our passport to the future." Inspiring for classrooms, students and educators alike. Available on boards, coasters, keyrings, rulers, door hangers and phone stands.', 'Watercolour school supplies and a quote on education', 'teachers, principals, graduates, students', '/designs/school_003/a3.webp', '/designs/pages/b10-5.webp', 'Teacher appreciation watercolour theme; different texts per piece: 300 board ''Teaching kids to count is fine, but teaching them what counts is best'', round board ''The best teachers teach from the heart not from the book'', A4 is a fill in ''Best Teacher Award'' certificate, round coaster ''Best teacher ever'', cup ''Happy teacher''s day'', ruler 30 ''The art of teaching is the art of assisting discovery''. No buttons on this page.', 70),
  ('SCHOOL_004', 'Arrive Alive Road Safety', (select id from public.themes where name = 'School and Kids'), 'en', 'Let''s play Arrive Alive!', 'Bright yellow and orange roads wind past road signs, traffic lights and cartoon children in this cheerful "Let''s play Arrive Alive!" design. A fun way to teach little ones road safety at home or in the classroom. Choose from boards, coasters, keyrings, rulers, door hangers and phone stands.', 'A cheerful road safety game for young learners', 'kids, teachers, schools, driving instructors', '/designs/school_004/a3.webp', '/designs/pages/b10-6.webp', 'Road safety theme. A3 is an ''Arrive Alive'' board game with play instructions; 300 board ''Know your roadsigns, be safe!''; round board, A4 and cup ''Road Trip''. Square coaster is a noughts and crosses (tic tac toe) shape rather than a plain square. Uses the Arrive Alive name and logo; owner may want to check use of that campaign branding. No buttons on this page.', 71),
  ('SKOOL_001', 'Ons Werk Saam', (select id from public.themes where name = 'School and Kids'), 'af', 'Ons werk saam: wees gereed om te leer, wees vriendelik met almal, droom groot, steek jou hand op, sê asseblief en dankie, doen jou bes, gebruik jou verbeelding, luister vir jou juffrou', '''n Ry vrolike spotprentkinders met boeke, musieknote en kleurvolle syfers teen ''n hemelblou agtergrond, met die klasafsprake "Ons werk saam", van "droom groot" tot "luister vir jou juffrou". Ideaal vir die klaskamermuur of die kinderkamer. Beskikbaar op borde, onderleggers, sleutelringe, liniale, deurhangers en meer.', 'Vrolike klasafsprake vir juffrou se klaskamer', 'juffrouens, kleuterskole, ouers met skoolkinders', '/designs/skool_001/a3.webp', '/designs/pages/b10-7.webp', 'Afrikaans classroom theme; other texts: 300 board and ruler 15 ''Leer om te speel, speel om te leer'', A4 ''Almal reg oor die wêreld verstaan ''n glimlag!'', square coaster ''Na die sterre'', round coaster and keyring 1 ''Ware wonderlike onderwysers is moeilik om te vind en onmoontlik om te vergeet'', door hanger has a school morning checklist. No buttons on this page.', 72),
  ('SKOOL_002', 'Klaskamer Reëls', (select id from public.themes where name = 'School and Kids'), 'af', 'Klaskamer-reëls: wees gereed om te leer, wees vriendelik met almal, droom groot, steek jou hand op, sê asseblief en dankie, doen jou bes, gebruik jou verbeelding, luister vir jou onderwyser', 'Skoolgoed, ballonne, vlaggies, ''n aardbol en ''n appel in waterverf op wit grafiekpapier omring die klaskamerreëls, van "wees vriendelik met almal" tot "gebruik jou verbeelding". ''n Vrolike en duidelike herinnering vir enige klas. Kry dit op borde, onderleggers, sleutelringe, liniale en meer.', 'Kleurvolle klaskamerreëls vir onderwysers en hul leerders', 'onderwysers, skole, gesinne wat tuisonderrig gee', '/designs/skool_002/a3.webp', '/designs/pages/b10-8.webp', 'Detector did not read the order code; it is printed as SKOOL_002. Afrikaans back to school theme; other texts: 300 board ''In ons klas'' class rules, round board ''Terug skool toe'', A4 ''My eerste klas'' poem with fill in lines, cup ''''n Onderwyser is ''n ster wat ander leer om te skyn'', hexagon coaster ''Ons werk saam!'', square coaster ''My no 1''. No buttons on this page.', 73);

