-- Safety check: stops straight away if this is not the DF Elements database
do $$
begin
  if to_regclass('public.products') is null
     or to_regclass('public.expense_categories') is null
     or to_regclass('public.designs') is null then
    raise exception 'STOP: This is not the DF Elements database. Switch to the DF Elements project at the top of Supabase and run this again.';
  end if;
end $$;

-- DF Elements: donkey and farm boards (A4 and A3)
-- Run once in the Supabase SQL Editor, after the 13 files.

insert into public.designs (code, name, theme_id, language, wording, description, short_description, gift_for, image_url, review_notes, sort_order) values
  ('DONKIE_001', 'Oorwin Die Dag', (select id from public.themes where name = 'Karoo Hart'), 'af', 'Oorwin die dag, een stappie op ''n slag. Selfs ''n donkie kom by die water.', '"Oorwin die dag, een stappie op ''n slag." ''n Donkie leun oor die plaashek terwyl die son sag oor die grondpad en windpomp sak. ''n Bemoedigende boodskap vir enigiemand wat deur ''n moeilike tyd stap, op ''n A4 of A3 bord.', 'Een stappie op ''n slag, met ''n donkie by die plaashek', 'iemand wat swaar kry, jou pa, ''n nuwe begin', '/designs/donkie_001/a4.webp', 'Descriptions written by Claude, please check.', 200),
  ('DONKIE_002', 'Moenie Haastig Wees Nie', (select id from public.themes where name = 'Karoo Hart'), 'af', 'Moenie haastig wees nie, daar is altyd tyd vir die goed wat saak maak.', '"Moenie haastig wees nie, daar''s altyd tyd vir die goed wat saak maak." ''n Donkie stap rustig op ''n grondpad tussen die heuwels. ''n Sagte herinnering om stadiger te gaan en te geniet wat regtig belangrik is.', 'Daar is altyd tyd vir die goed wat saak maak', 'ouers, ''n besige vriendin, die stoep', '/designs/donkie_002/a4.webp', 'Descriptions written by Claude, please check.', 201),
  ('DONKIE_003', 'Hard Werk Soos ''n Donkie', (select id from public.themes where name = 'Karoo Hart'), 'af', 'Hard werk soos ''n donkie, rus soos ''n koning.', '"Hard werk soos ''n donkie, rus soos ''n koning." ''n Donkie met ''n wa vol hooi staan voor ou wit planke. Perfek vir die harde werker wat sy rus verdien het, in die kantoor, die werkswinkel of op die stoep.', 'Werk hard, rus soos ''n koning', 'harde werkers, jou pa, ''n aftrede', '/designs/donkie_003/a4.webp', 'Descriptions written by Claude, please check.', 202),
  ('DONKIE_004', 'Hou Aan', (select id from public.themes where name = 'Karoo Hart'), 'af', 'Hou aan, selfs as dit moeilik is. Die mooiste kom ná die swaarste pad.', '"Hou aan, selfs as dit moeilik is." ''n Nuuskierige donkie kyk reg na jou, met ''n houtbordjie wat sê die mooiste kom ná die swaarste pad. Moed en hoop, op hout gedruk.', 'Die mooiste kom ná die swaarste pad', 'iemand wat swaar kry, ''n vriend, ''n student', '/designs/donkie_004/a4.webp', 'Descriptions written by Claude, please check.', 203),
  ('DONKIE_005', 'Gee Nooit Op Nie', (select id from public.themes where name = 'Karoo Hart'), 'af', '''n Donkie dra nie meer as wat hy kan nie, maar hy gee nooit op nie.', '"''n Donkie dra nie meer as wat hy kan nie, maar hy gee nooit op nie." ''n Donkie met sy saalsakke wei langs die draad in die veld. Vir die mense wat altyd aanhou, maak nie saak hoe swaar die vrag is nie.', 'Hy dra net wat hy kan, maar gee nooit op nie', 'boere, ''n sterk vriendin, ''n afgetredene', '/designs/donkie_005/a4.webp', 'Descriptions written by Claude, please check.', 204),
  ('DONKIE_006', 'Dankbaar Vir Klein Goed', (select id from public.themes where name = 'Karoo Hart'), 'af', 'Dankbaar vir klein goed, groot seëninge, en sterk skouers soos ''n donkie s''n.', '"Dankbaar vir klein goed, groot seëninge, en sterk skouers soos ''n donkie s''n." ''n Glimlaggende donkie tussen ou melkkanne en blomme. ''n Warm plaasstuk vir die kombuis of die voorstoep.', 'Dankbaar vir klein goed en groot seëninge', 'die kombuis, jou ma, ''n huisinwyding', '/designs/donkie_006/a4.webp', 'Descriptions written by Claude, please check.', 205),
  ('DONKIE_007', 'Voete Op Die Grond', (select id from public.themes where name = 'Karoo Hart'), 'af', 'Voete op die grond. Oë op die horison. Hart vol vertroue.', '"Voete op die grond. Oë op die horison. Hart vol vertroue." ''n Donkie by die hek met ''n windpomp in die goue sonsondergang. Rustig en vol hoop, mooi vir enige muur in die huis.', 'Voete op die grond, hart vol vertroue', '''n nuwe huis, ''n gradeplegtigheid, wie die platteland liefhet', '/designs/donkie_007/a4.webp', 'Descriptions written by Claude, please check.', 206),
  ('DONKIE_008', 'Donkie Met Saalsakke', (select id from public.themes where name = 'Karoo Hart'), 'af', '', '''n Donkie met leer saalsakke stap op ''n grondpad langs die ou draad, in warm sepia plaaskleure. Sonder woorde, net die rustige platteland, vir wie die Karoo en sy donkies liefhet.', 'Die rustige platteland in warm sepia kleure', 'wie die platteland liefhet, ''n plaaskombuis, donkie liefhebbers', '/designs/donkie_008/a4.webp', 'Descriptions written by Claude, please check.', 207),
  ('PLAAS_001', 'Waar Geloof Geplant Word', (select id from public.themes where name = 'Faith and Blessings'), 'af', 'Waar geloof geplant word, word seën geoes. Die Here voorsien, selfs wanneer die veld droog lyk.', '"Waar geloof geplant word, word seën geoes." ''n Windpomp, ''n ou plaashuis en ''n Nguni bees op ''n sagte houtagtergrond, met die belofte dat die Here voorsien, selfs wanneer die veld droog lyk. ''n Stil getuienis vir die boer se huis.', 'Die Here voorsien, selfs wanneer die veld droog lyk', 'boere, jou pa, ''n plaashuis', '/designs/plaas_001/a4.webp', 'Descriptions written by Claude, please check. The board quotes Jeremia 29:11, but that verse is about the plans God has for you, not about faith being sown and reaped. Check the reference.', 208),
  ('PLAAS_002', 'Boer Met Hoop', (select id from public.themes where name = 'Faith and Blessings'), 'af', 'Boer met hoop, oes met dankbaarheid. Moenie moed verloor nie, die mooiste oeste vat tyd. Werk hard. Bid harder. Vertrou altyd. God is getrou.', '"Boer met hoop, oes met dankbaarheid." ''n Ou groen trekker en windpomp onder die woorde werk hard, bid harder, vertrou altyd. ''n Bemoediging vir elke boer wat weet die mooiste oeste vat tyd.', 'Werk hard, bid harder, vertrou altyd', 'boere, ''n trekker liefhebber, Vadersdag', '/designs/plaas_002/a4.webp', 'Descriptions written by Claude, please check.', 209),
  ('PLAAS_003', 'Hou Aan Glo', (select id from public.themes where name = 'Faith and Blessings'), 'af', 'Waar geloof geplant word, word seën geoes. Die Here voorsien, selfs wanneer die pad moeilik is. Hou aan glo, hou aan loop, Hy is altyd daar.', '"Hou aan glo, hou aan loop, Hy is altyd daar." ''n Plaashond wag by die hek langs ''n melkkan vol proteas, met ''n windpomp en beeste in die goue sonsondergang. Warm, hoopvol en vol platteland.', 'Hou aan glo, hou aan loop, Hy is altyd daar', '''n vriend in ''n moeilike tyd, jou ma, ''n plaashuis', '/designs/plaas_003/a4.webp', 'Descriptions written by Claude, please check.', 210),
  ('PLAAS_004', 'Hier Is Koffie Warm', (select id from public.themes where name = 'Coffee'), 'af', 'Hier is koffie warm, die hek oop en harte welkom.', '"Hier is koffie warm, die hek oop en harte welkom." ''n Ou plaashek en ''n dampende koppie koffie op wit planke. Die perfekte welkom vir die voordeur, die kombuis of die koffiehoekie.', 'Die koffie is warm en die hek is oop', '''n nuwe huis, koffie liefhebbers, die kombuis', '/designs/plaas_004/a4.webp', 'Descriptions written by Claude, please check.', 211)
on conflict (code) do nothing;

insert into public.products (sku, name, variant, type, theme_id, short_description, care, material, price, made_to_order, is_new, image_url, sort_order, design_id, format_key, cost_item_id)
select 'DONKIE_001_A3', 'Oorwin Die Dag', 'A3 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Een stappie op ''n slag, met ''n donkie by die plaashek', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/donkie_001/a3.webp', 4001, (select id from public.designs where code = 'DONKIE_001'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'DONKIE_001_A4', 'Oorwin Die Dag', 'A4 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Een stappie op ''n slag, met ''n donkie by die plaashek', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/donkie_001/a4.webp', 4002, (select id from public.designs where code = 'DONKIE_001'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'DONKIE_002_A3', 'Moenie Haastig Wees Nie', 'A3 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Daar is altyd tyd vir die goed wat saak maak', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/donkie_002/a3.webp', 4011, (select id from public.designs where code = 'DONKIE_002'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'DONKIE_002_A4', 'Moenie Haastig Wees Nie', 'A4 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Daar is altyd tyd vir die goed wat saak maak', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/donkie_002/a4.webp', 4012, (select id from public.designs where code = 'DONKIE_002'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'DONKIE_003_A3', 'Hard Werk Soos ''n Donkie', 'A3 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Werk hard, rus soos ''n koning', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/donkie_003/a3.webp', 4021, (select id from public.designs where code = 'DONKIE_003'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'DONKIE_003_A4', 'Hard Werk Soos ''n Donkie', 'A4 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Werk hard, rus soos ''n koning', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/donkie_003/a4.webp', 4022, (select id from public.designs where code = 'DONKIE_003'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'DONKIE_004_A3', 'Hou Aan', 'A3 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Die mooiste kom ná die swaarste pad', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/donkie_004/a3.webp', 4031, (select id from public.designs where code = 'DONKIE_004'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'DONKIE_004_A4', 'Hou Aan', 'A4 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Die mooiste kom ná die swaarste pad', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/donkie_004/a4.webp', 4032, (select id from public.designs where code = 'DONKIE_004'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'DONKIE_005_A3', 'Gee Nooit Op Nie', 'A3 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Hy dra net wat hy kan, maar gee nooit op nie', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/donkie_005/a3.webp', 4041, (select id from public.designs where code = 'DONKIE_005'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'DONKIE_005_A4', 'Gee Nooit Op Nie', 'A4 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Hy dra net wat hy kan, maar gee nooit op nie', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/donkie_005/a4.webp', 4042, (select id from public.designs where code = 'DONKIE_005'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'DONKIE_006_A3', 'Dankbaar Vir Klein Goed', 'A3 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Dankbaar vir klein goed en groot seëninge', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/donkie_006/a3.webp', 4051, (select id from public.designs where code = 'DONKIE_006'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'DONKIE_006_A4', 'Dankbaar Vir Klein Goed', 'A4 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Dankbaar vir klein goed en groot seëninge', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/donkie_006/a4.webp', 4052, (select id from public.designs where code = 'DONKIE_006'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'DONKIE_007_A3', 'Voete Op Die Grond', 'A3 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Voete op die grond, hart vol vertroue', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/donkie_007/a3.webp', 4061, (select id from public.designs where code = 'DONKIE_007'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'DONKIE_007_A4', 'Voete Op Die Grond', 'A4 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Voete op die grond, hart vol vertroue', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/donkie_007/a4.webp', 4062, (select id from public.designs where code = 'DONKIE_007'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'DONKIE_008_A3', 'Donkie Met Saalsakke', 'A3 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Die rustige platteland in warm sepia kleure', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/donkie_008/a3.webp', 4071, (select id from public.designs where code = 'DONKIE_008'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'DONKIE_008_A4', 'Donkie Met Saalsakke', 'A4 board', 'board', (select id from public.themes where name = 'Karoo Hart'), 'Die rustige platteland in warm sepia kleure', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/donkie_008/a4.webp', 4072, (select id from public.designs where code = 'DONKIE_008'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'PLAAS_001_A3', 'Waar Geloof Geplant Word', 'A3 board', 'board', (select id from public.themes where name = 'Faith and Blessings'), 'Die Here voorsien, selfs wanneer die veld droog lyk', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/plaas_001/a3.webp', 4081, (select id from public.designs where code = 'PLAAS_001'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'PLAAS_001_A4', 'Waar Geloof Geplant Word', 'A4 board', 'board', (select id from public.themes where name = 'Faith and Blessings'), 'Die Here voorsien, selfs wanneer die veld droog lyk', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/plaas_001/a4.webp', 4082, (select id from public.designs where code = 'PLAAS_001'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'PLAAS_002_A3', 'Boer Met Hoop', 'A3 board', 'board', (select id from public.themes where name = 'Faith and Blessings'), 'Werk hard, bid harder, vertrou altyd', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/plaas_002/a3.webp', 4091, (select id from public.designs where code = 'PLAAS_002'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'PLAAS_002_A4', 'Boer Met Hoop', 'A4 board', 'board', (select id from public.themes where name = 'Faith and Blessings'), 'Werk hard, bid harder, vertrou altyd', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/plaas_002/a4.webp', 4092, (select id from public.designs where code = 'PLAAS_002'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'PLAAS_003_A3', 'Hou Aan Glo', 'A3 board', 'board', (select id from public.themes where name = 'Faith and Blessings'), 'Hou aan glo, hou aan loop, Hy is altyd daar', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/plaas_003/a3.webp', 4101, (select id from public.designs where code = 'PLAAS_003'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'PLAAS_003_A4', 'Hou Aan Glo', 'A4 board', 'board', (select id from public.themes where name = 'Faith and Blessings'), 'Hou aan glo, hou aan loop, Hy is altyd daar', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/plaas_003/a4.webp', 4102, (select id from public.designs where code = 'PLAAS_003'), 'a4', (select cost_item_id from public.formats where key = 'a4')
union all
select 'PLAAS_004_A3', 'Hier Is Koffie Warm', 'A3 board', 'board', (select id from public.themes where name = 'Coffee'), 'Die koffie is warm en die hek is oop', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a3'), true, true, '/designs/plaas_004/a3.webp', 4111, (select id from public.designs where code = 'PLAAS_004'), 'a3', (select cost_item_id from public.formats where key = 'a3')
union all
select 'PLAAS_004_A4', 'Hier Is Koffie Warm', 'A4 board', 'board', (select id from public.themes where name = 'Coffee'), 'Die koffie is warm en die hek is oop', 'Wipe clean with a soft damp cloth. Keep out of standing water and the dishwasher.', 'MDF, UV printed.', (select price from public.formats where key = 'a4'), true, true, '/designs/plaas_004/a4.webp', 4112, (select id from public.designs where code = 'PLAAS_004'), 'a4', (select cost_item_id from public.formats where key = 'a4')
on conflict (sku) do nothing;

insert into public.wholesale_prices (product_id, price)
select p.id, f.trade_price from public.products p join public.formats f on f.key = p.format_key
where (p.sku like 'DONKIE_%' or p.sku like 'PLAAS_%') and f.trade_price is not null
  and not exists (select 1 from public.wholesale_prices w where w.product_id = p.id);
